name: Flipper Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Flipper Application Package (.fap)
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
  